const LIST_AUTO = [
  {
    id: 'el1',
    img: 'img/listAuto/el1.png',
    type: 'Грузовик',
    classType: 'truk',
    name: 'Opel COMBO Airco Elct Ramen Stuurbediening',
    manufacturer: 'Opel',
    yearProd: 2015,
    weight: 2000,
    mileage: 490574,
    transmissionType: 'automatic',
    location: 'Garage van Nierop Netherlands',
    country: 'Нидерланды',
    price: 1500,
    adType: 'sale'
  },
  {
    id: 'el2',
    img: 'img/listAuto/el2.png',
    type: 'Грузовик',
    classType: 'truk',
    name: 'Mercedes-Benz V 250 d lang Avantgarde Edition 360°',
    manufacturer: 'Mercedes-benz',
    yearProd: 2015,
    weight: 2000,
    mileage: 490574,
    transmissionType: 'automatic',
    location: 'Jingmen Street, Shanghai, China',
    country: 'Китай',
    price: 54300,
    adType: 'sale'
  },
  {
    id: 'el3',
    img: 'img/listAuto/el3.png',
    type: 'Автобус',
    classType: 'bus',
    name: 'Cobus Mercedes Benz 2700 S',
    manufacturer: 'Mercedes-benz',
    yearProd: 2015,
    weight: 2000,
    mileage: 490574,
    transmissionType: 'manual',
    location: 'Beijing Road, Guangzhou, China',
    country: 'Китай',
    price: 43580,
    adType: 'sale'
  },
  {
    id: 'el4',
    img: 'img/listAuto/el4.png',
    type: 'Автобус',
    classType: 'bus',
    name: 'Setra 317 UL-GT/Klima/6 Gang/65 Sitz',
    manufacturer: 'Scania',
    yearProd: 2011,
    weight: 4500,
    mileage: 320000,
    transmissionType: 'manual',
    location: 'Shibuya-ku, Tokyo, Japan',
    country: 'Япония',
    price: 13900,
    adType: 'auction'
  },
  {
    id: 'el5',
    img: 'img/listAuto/el5.png',
    type: 'Грузовик',
    classType: 'truk',
    name: 'Nissan Eco T 100 Paardenvervoer',
    manufacturer: 'Nissan',
    yearProd: 2015,
    weight: 2000,
    mileage: 490574,
    transmissionType: 'manual',
    location: 'Minato-ku, Osaka, Japan',
    country: 'Япония',
    price: 3100,
    adType: 'auction'
  },
  {
    id: 'el6',
    img: 'img/listAuto/el6.png',
    type: 'Грузовик',
    classType: 'truk',
    name: 'Renault Mascott 130.35 DC 363',
    manufacturer: 'Renault',
    yearProd: 2015,
    weight: 2000,
    mileage: 490574,
    transmissionType: 'manual',
    location: 'Goethestraße, Berlin, Germany',
    country: 'Германия',
    price: 4850,
    adType: 'request'
  },
  {
    id: 'el7',
    img: 'img/listAuto/el7.png',
    type: 'Хэтчбек',
    classType: 'hatchback',
    name: 'Volkswagen Golf Plus VI Team',
    manufacturer: 'Volkswagen',
    yearProd: 2010,
    weight: 900,
    mileage: 49000,
    transmissionType: 'manual',
    location: 'Elm Street, Brooklyn, NY, USA',
    country: 'США',
    price: 7990,
    adType: 'leasing'
  },
  {
    id: 'el8',
    img: 'img/listAuto/el8.png',
    type: 'Универсал',
    classType: 'universal',
    name: 'Audi A4 Avant 2.0 TDI S tronic S-Line',
    manufacturer: 'Audi',
    yearProd: 2017,
    weight: 1000,
    mileage: 138000,
    transmissionType: 'automatic',
    location: 'Goethestraße, Berlin, Germany',
    country: 'Германия',
    price: 18990,
    adType: 'leasing'
  },
  {
    id: 'el9',
    img: 'img/listAuto/el9.png',
    type: 'Универсал',
    classType: 'universal',
    name: 'Ford Focus Wagon 1.6 tdci',
    manufacturer: 'Ford',
    yearProd: 2006,
    weight: 850,
    mileage: 130000,
    transmissionType: 'automatic',
    location: 'Jongno-gu, Seoul, South Korea',
    country: 'Корея',
    price: 2500,
    adType: 'rent'
  },
  {
    id: 'el10',
    img: 'img/listAuto/el10.png',
    type: 'Седан',
    classType: 'sedan',
    name: 'Fiat Fiat Tipo 1.6 Mjet',
    manufacturer: 'Fiat',
    yearProd: 2017,
    weight: 700,
    mileage: 110000,
    transmissionType: 'automatic',
    location: 'Corso Buenos Aires, Milan, Italy',
    country: 'Италия',
    price: 10400,
    adType: 'rent'
  },
  {
    id: 'el11',
    img: 'img/listAuto/el11.png',
    type: 'Кроссовер',
    classType: 'сrossover',
    name: 'Nissan Qashqai II 2.0 CVT',
    manufacturer: 'Nissan',
    yearProd: 2022,
    weight: 1100,
    mileage: 88000,
    transmissionType: 'automatic',
    location: 'Voskresenskaya Street, Kazan, Russia',
    country: 'Россия',
    price: 10400,
    adType: 'sale'
  },
  {
    id: 'el12',
    img: 'img/listAuto/el12.png',
    type: 'Кроссовер',
    classType: 'сrossover',
    name: 'Volvo XC60 2.4 AT',
    manufacturer: 'Volvo',
    yearProd: 2014,
    weight: 1300,
    mileage: 317500,
    transmissionType: 'automatic',
    location: 'Lenina Street, Voronezh, Russia',
    country: 'Россия',
    price: 6900,
    adType: 'sale'
  },
  {
    id: 'el13',
    img: 'img/listAuto/el13.png',
    type: 'Грузовик',
    classType: 'truk',
    name: 'MAN TGS 26.350',
    manufacturer: 'Man',
    yearProd: 2010,
    weight: 3300,
    mileage: 525400,
    transmissionType: 'manual',
    location: 'Petrovskaya, Rostov-on-Don, Russia',
    country: 'Россия',
    price: 45900,
    adType: 'rent'
  },
  {
    id: 'el14',
    img: 'img/listAuto/el14.png',
    type: 'Внедорожник',
    classType: 'suv',
    name: 'Ford Explorer',
    manufacturer: 'Ford',
    yearProd: 2016,
    weight: 1700,
    mileage: 234400,
    transmissionType: 'manual',
    location: 'Main Street, Toledo, Ohio, USA',
    country: 'США',
    price: 12399,
    adType: 'request'
  },
  {
    id: 'el15',
    img: 'img/listAuto/el15.png',
    type: 'Грузовик',
    classType: 'truk',
    name: 'Iveco Daily',
    manufacturer: 'Iveco',
    yearProd: 2023,
    weight: 2400,
    mileage: 61000,
    transmissionType: 'manual',
    location: 'Pobedy Street, Belgorod, Russia',
    country: 'Россия',
    price: 9999,
    adType: 'sale'
  },
  {
    id: 'el16',
    img: 'img/listAuto/el16.png',
    type: 'Автобус',
    classType: 'bus',
    name: 'Van Hool T916 Astron',
    manufacturer: 'Van-hool',
    yearProd: 2012,
    weight: 4400,
    mileage: 657089,
    transmissionType: 'manual',
    location: 'Sienkiewicza Street, Łódź, Poland',
    country: 'Польша',
    price: 23450,
    adType: 'sale'
  },
  {
    id: 'el17',
    img: 'img/listAuto/el17.png',
    type: 'Седан',
    classType: 'sedan',
    name: 'Volkswagen Polo V',
    manufacturer: 'volkswagen',
    yearProd: 2018,
    weight: 700,
    mileage: 120000,
    transmissionType: 'automatic',
    location: 'Karl-Marx-Allee, Berlin, Germany',
    country: 'Германия',
    price: 6770,
    adType: 'sale'
  },
  {
    id: 'el18',
    img: 'img/listAuto/el18.png',
    type: 'Седан',
    classType: 'sedan',
    name: 'Volvo S40',
    manufacturer: 'Volvo',
    yearProd: 2008,
    weight: 800,
    mileage: 510000,
    transmissionType: 'automatic',
    location: 'Pushkinskaya Street, Novosibirsk, Russia',
    country: 'Россия',
    price: 4770,
    adType: 'leasing'
  },
  {
    id: 'el19',
    img: 'img/listAuto/el19.png',
    type: 'Внедорожник',
    classType: 'suv',
    name: 'Renault Koleos',
    manufacturer: 'renault',
    yearProd: 2018,
    weight: 1300,
    mileage: 125400,
    transmissionType: 'automatic',
    location: 'Tverskaya Street, Moscow, Russia',
    country: 'Россия',
    price: 6510,
    adType: 'rent'
  },
  {
    id: 'el20',
    img: 'img/listAuto/el20.png',
    type: 'Универсал',
    classType: 'universal',
    name: 'Opel Astra',
    manufacturer: 'opel',
    yearProd: 2014,
    weight: 850,
    mileage: 333000,
    transmissionType: 'manual',
    location: 'Beijing Road, Beijing, China',
    country: 'Китай',
    price: 3510,
    adType: 'sale'
  },
];